import type { ColumnRegular } from '@revolist/revogrid';
import type { KanbanUseCaseScenario } from '../kanban-use-case-model';

const columns: ColumnRegular[] = [
  { prop: 'id', name: 'Content ID', size: 104, sortable: true, filter: true },
  { prop: 'title', name: 'Content', size: 260, sortable: true, filter: true },
  { prop: 'campaign', name: 'Campaign', size: 156, sortable: true, filter: true },
  { prop: 'channel', name: 'Channel', size: 118, sortable: true, filter: true },
  { prop: 'locale', name: 'Locale', size: 86, sortable: true, filter: true },
  { prop: 'legalReviewer', name: 'Legal reviewer', size: 142, sortable: true, filter: true },
  { prop: 'publishDate', name: 'Publish date', size: 116, sortable: true },
  { prop: 'owner', name: 'Owner', size: 132, sortable: true, filter: true },
  { prop: 'status', name: 'Stage', size: 110, sortable: true, filter: true },
];

export const CONTENT_APPROVALS_SCENARIO = {
  id: 'content-approvals',
  cardPresentation: 'editorial-approval',
  useSwimlanes: false,
  colorScheme: 'light',
  layout: { cardRowHeight: 286, swimlaneWidth: 172, collapsedSwimlaneWidth: 44 },
  eyebrow: 'Content operations · Fall 2026',
  title: 'Move every story from brief to publish with confidence',
  description: 'Give writers, designers, reviewers, and channel owners one shared view of what customers will see, who needs to approve it, and which promise is at risk.',
  attention: {
    label: 'Approval queue above capacity',
    detail: 'Four pieces are waiting on a three-slot approval limit; the French pricing page needs legal sign-off by Aug 27 to protect the Sep 2 launch.',
    tone: 'risk',
  },
  metrics: [
    { label: 'Campaign readiness', value: '71%', tone: 'attention' },
    { label: 'Approval queue', value: '4 / 3', tone: 'risk' },
    { label: 'Next publish', value: 'Aug 26', tone: 'neutral' },
  ],
  workflowColumns: [
    { prop: 'briefed', name: 'Briefed', size: 334 },
    { prop: 'creating', name: 'Creating', size: 334 },
    { prop: 'editorial', name: 'Editorial review', size: 334 },
    { prop: 'approval', name: 'Approval', size: 334, wipLimit: 3 },
    { prop: 'publish', name: 'Scheduled / live', size: 334 },
  ],
  swimlanes: [
    { id: 'campaigns', title: 'Launch campaigns', collapsible: true, wipLimits: { approval: 1 } },
    { id: 'education', title: 'Customer education', collapsible: true },
  ],
  wipBehavior: 'warn',
  columns,
  cards: [
    {
      id: 'CA-301',
      title: 'Localize the fall launch narrative',
      description: 'Turn the core product story into a brief every regional team can use.',
      status: 'briefed',
      lane: 'campaigns',
      owner: 'Maya Chen',
      assignees: ['Maya Chen', 'Iris Bell'],
      priority: 'Medium',
      label: 'Fall launch',
      progress: 15,
      dueDate: 'Aug 18',
      order: 1000,
      campaign: 'Fall 2026 Launch',
      channel: 'Multi-channel',
      locale: 'Global',
      legalReviewer: 'Dana Cole',
      publishDate: '2026-09-02',
      publishState: 'Planned',
      handoff: 'Product marketing → Brand',
      context: 'Publish Sep 2 · Multi-channel · Global',
    },
    {
      id: 'CA-304',
      title: 'Cut the product reveal video',
      description: 'Shape the two-minute launch story around customer outcomes, not features.',
      status: 'creating',
      lane: 'campaigns',
      owner: 'Sofia Marin',
      assignees: ['Sofia Marin', 'Iris Bell'],
      priority: 'High',
      label: 'Fall launch',
      progress: 55,
      dueDate: 'Aug 20',
      order: 1000,
      campaign: 'Fall 2026 Launch',
      channel: 'Video',
      locale: 'en-US',
      legalReviewer: 'Marco Ruiz',
      publishDate: '2026-09-02',
      publishState: 'Planned',
      handoff: 'Creative → Editorial',
      context: 'Publish Sep 2 · Video · en-US',
    },
    {
      id: 'CA-306',
      title: 'Build the launch email sequence',
      description: 'Write announcement, proof, and activation emails as one coherent journey.',
      status: 'creating',
      lane: 'campaigns',
      owner: 'Ava Morgan',
      assignees: ['Ava Morgan', 'Theo Brooks'],
      priority: 'Medium',
      label: 'Fall launch',
      progress: 65,
      dueDate: 'Aug 21',
      order: 2000,
      campaign: 'Fall 2026 Launch',
      channel: 'Email',
      locale: 'en-US',
      legalReviewer: 'Dana Cole',
      publishDate: '2026-09-02',
      publishState: 'Planned',
      handoff: 'Lifecycle → Editorial',
      context: 'Publish Sep 2 · Email · en-US',
    },
    {
      id: 'CA-309',
      title: 'Review the partner comparison page',
      description: 'Check every claim against current packaging and partner agreements.',
      status: 'editorial',
      lane: 'campaigns',
      owner: 'Noah Grant',
      assignees: ['Noah Grant', 'Maya Chen'],
      priority: 'High',
      label: 'Fall launch',
      progress: 80,
      dueDate: 'Aug 24',
      order: 1000,
      campaign: 'Fall 2026 Launch',
      channel: 'Web',
      locale: 'en-US',
      legalReviewer: 'Dana Cole',
      publishDate: '2026-09-02',
      publishState: 'Planned',
      handoff: 'Editorial → Legal',
      context: 'Publish Sep 2 · Web · en-US',
    },
    {
      id: 'CA-312',
      title: 'Approve the French pricing page',
      description: 'Confirm translated offer terms, tax language, and promotional expiry.',
      status: 'approval',
      lane: 'campaigns',
      owner: 'Camille Laurent',
      assignees: ['Camille Laurent', 'Dana Cole'],
      priority: 'Critical',
      label: 'Fall launch',
      progress: 92,
      dueDate: 'Aug 27',
      order: 1000,
      campaign: 'Fall 2026 Launch',
      channel: 'Web',
      locale: 'fr-FR',
      legalReviewer: 'Dana Cole',
      publishDate: '2026-09-02',
      publishState: 'Pending approval',
      handoff: 'Localization → Legal',
      context: 'Publish Sep 2 · Web · fr-FR',
      risk: 'Approval after Aug 27 removes the localized page from launch day.',
    },
    {
      id: 'CA-314',
      title: 'Clear the customer proof montage',
      description: 'Verify usage rights, captions, and quote context for paid placements.',
      status: 'approval',
      lane: 'campaigns',
      owner: 'Sofia Marin',
      assignees: ['Sofia Marin', 'Marco Ruiz'],
      priority: 'High',
      label: 'Customer proof',
      progress: 85,
      dueDate: 'Aug 28',
      order: 2000,
      campaign: 'Fall 2026 Launch',
      channel: 'Paid social',
      locale: 'en-US',
      legalReviewer: 'Marco Ruiz',
      publishDate: '2026-09-03',
      publishState: 'Pending approval',
      handoff: 'Brand → Legal',
      context: 'Publish Sep 3 · Paid social · en-US',
      risk: 'One customer release form still lacks the paid-media clause.',
    },
    {
      id: 'CA-317',
      title: 'Schedule the launch-day social thread',
      description: 'Sequence product moments, customer proof, and support links for release day.',
      status: 'publish',
      lane: 'campaigns',
      owner: 'Lena Ortiz',
      assignees: ['Lena Ortiz', 'Ava Morgan'],
      priority: 'Medium',
      label: 'Fall launch',
      progress: 96,
      dueDate: 'Aug 31',
      order: 1000,
      campaign: 'Fall 2026 Launch',
      channel: 'Social',
      locale: 'en-US',
      legalReviewer: 'Marco Ruiz',
      publishDate: '2026-09-02',
      publishState: 'Scheduled',
      handoff: 'Social → Community',
      context: 'Publish Sep 2 · Social · en-US',
    },
    {
      id: 'CA-290',
      title: 'Publish the early-access customer story',
      description: 'Share how the beta team shortened handoffs without adding meetings.',
      status: 'publish',
      lane: 'campaigns',
      owner: 'Noah Grant',
      assignees: ['Noah Grant', 'Lena Ortiz'],
      priority: 'Low',
      label: 'Early access',
      progress: 100,
      dueDate: 'Aug 20',
      order: 2000,
      campaign: 'Early Access Proof',
      channel: 'Blog',
      locale: 'en-US',
      legalReviewer: 'Dana Cole',
      publishDate: '2026-08-20',
      publishState: 'Live',
      handoff: 'Editorial → Community',
      context: 'Published Aug 20 · Blog · en-US',
    },
    {
      id: 'CA-321',
      title: 'Outline the returns policy explainer',
      description: 'Answer the five questions customers ask most before starting a return.',
      status: 'briefed',
      lane: 'education',
      owner: 'Nora Reed',
      assignees: ['Nora Reed', 'Ava Morgan'],
      priority: 'Medium',
      label: 'Customer education',
      progress: 10,
      dueDate: 'Aug 19',
      order: 1000,
      campaign: 'Customer Education',
      channel: 'Help center',
      locale: 'en-GB',
      legalReviewer: 'Dana Cole',
      publishDate: '2026-09-09',
      publishState: 'Planned',
      handoff: 'Support → Content',
      context: 'Publish Sep 9 · Help center · en-GB',
    },
    {
      id: 'CA-324',
      title: 'Refresh the data export guide',
      description: 'Replace technical steps with a task-led walkthrough and clear examples.',
      status: 'creating',
      lane: 'education',
      owner: 'Sam Patel',
      assignees: ['Sam Patel', 'Elena Park'],
      priority: 'Medium',
      label: 'Customer education',
      progress: 50,
      dueDate: 'Aug 24',
      order: 1000,
      campaign: 'Customer Education',
      channel: 'Help center',
      locale: 'en-US',
      legalReviewer: 'Marco Ruiz',
      publishDate: '2026-09-10',
      publishState: 'Planned',
      handoff: 'Docs → Technical review',
      context: 'Publish Sep 10 · Help center · en-US',
    },
    {
      id: 'CA-326',
      title: 'Record the admin onboarding walkthrough',
      description: 'Show a new admin reaching first value in under seven minutes.',
      status: 'creating',
      lane: 'education',
      owner: 'Sofia Marin',
      assignees: ['Sofia Marin', 'Nora Reed'],
      priority: 'Medium',
      label: 'Onboarding',
      progress: 45,
      dueDate: 'Aug 25',
      order: 2000,
      campaign: 'Admin Onboarding',
      channel: 'Academy video',
      locale: 'en-US',
      legalReviewer: 'Dana Cole',
      publishDate: '2026-09-11',
      publishState: 'Planned',
      handoff: 'Video → Accessibility',
      context: 'Publish Sep 11 · Academy video · en-US',
    },
    {
      id: 'CA-329',
      title: 'Edit the security FAQ update',
      description: 'Make the new encryption and retention answers accurate and reassuring.',
      status: 'editorial',
      lane: 'education',
      owner: 'Sam Patel',
      assignees: ['Sam Patel', 'Priya Nair'],
      priority: 'High',
      label: 'Trust center',
      progress: 78,
      dueDate: 'Aug 26',
      order: 1000,
      campaign: 'Trust Education',
      channel: 'Trust center',
      locale: 'Global',
      legalReviewer: 'Marco Ruiz',
      publishDate: '2026-09-04',
      publishState: 'Planned',
      handoff: 'Security → Editorial',
      context: 'Publish Sep 4 · Trust center · Global',
    },
    {
      id: 'CA-332',
      title: 'Approve cookie consent guidance',
      description: 'Sign off regional wording for analytics choices and preference changes.',
      status: 'approval',
      lane: 'education',
      owner: 'Greta Vogel',
      assignees: ['Greta Vogel', 'Dana Cole'],
      priority: 'High',
      label: 'Privacy',
      progress: 88,
      dueDate: 'Aug 28',
      order: 1000,
      campaign: 'Privacy Education',
      channel: 'Help center',
      locale: 'de-DE',
      legalReviewer: 'Dana Cole',
      publishDate: '2026-09-07',
      publishState: 'Pending approval',
      handoff: 'Localization → Privacy',
      context: 'Publish Sep 7 · Help center · de-DE',
      risk: 'Regional privacy review has one open analytics wording question.',
    },
    {
      id: 'CA-334',
      title: 'Sign off the AI feature disclosure',
      description: 'Confirm customers can understand when assistance is generated and why.',
      status: 'approval',
      lane: 'education',
      owner: 'Ava Morgan',
      assignees: ['Ava Morgan', 'Marco Ruiz'],
      priority: 'High',
      label: 'Responsible AI',
      progress: 90,
      dueDate: 'Aug 29',
      order: 2000,
      campaign: 'AI Transparency',
      channel: 'Product UI',
      locale: 'en-US',
      legalReviewer: 'Marco Ruiz',
      publishDate: '2026-09-08',
      publishState: 'Pending approval',
      handoff: 'Product → Legal',
      context: 'Publish Sep 8 · Product UI · en-US',
    },
    {
      id: 'CA-337',
      title: 'Schedule the renewal checklist email',
      description: 'Send account owners a simple readiness list before renewal review.',
      status: 'publish',
      lane: 'education',
      owner: 'Ava Morgan',
      assignees: ['Ava Morgan', 'Theo Brooks'],
      priority: 'Medium',
      label: 'Lifecycle',
      progress: 97,
      dueDate: 'Aug 26',
      order: 1000,
      campaign: 'Renewal Readiness',
      channel: 'Email',
      locale: 'en-US',
      legalReviewer: 'Dana Cole',
      publishDate: '2026-08-26',
      publishState: 'Scheduled',
      handoff: 'Lifecycle → Customer success',
      context: 'Publish Aug 26 · Email · en-US',
    },
    {
      id: 'CA-318',
      title: 'Publish the accessibility release notes',
      description: 'Explain the latest keyboard, contrast, and screen-reader improvements.',
      status: 'publish',
      lane: 'education',
      owner: 'Nora Reed',
      assignees: ['Nora Reed', 'Sam Patel'],
      priority: 'Low',
      label: 'Accessibility',
      progress: 100,
      dueDate: 'Aug 15',
      order: 2000,
      campaign: 'Product Education',
      channel: 'Release notes',
      locale: 'Global',
      legalReviewer: 'Marco Ruiz',
      publishDate: '2026-08-15',
      publishState: 'Live',
      handoff: 'Docs → Support',
      context: 'Published Aug 15 · Release notes · Global',
    },
  ],
} satisfies KanbanUseCaseScenario;
