import type { ColumnRegular } from '@revolist/revogrid';
import type { KanbanUseCaseScenario } from '../kanban-use-case-model';

const columns: ColumnRegular[] = [
  { prop: 'id', name: 'Account ID', size: 112, sortable: true, filter: true },
  { prop: 'account', name: 'Account', size: 186, sortable: true, filter: true },
  { prop: 'arr', name: 'ARR', size: 100, sortable: true, filter: true },
  { prop: 'owner', name: 'Owner', size: 142, sortable: true, filter: true },
  { prop: 'status', name: 'Stage', size: 132, sortable: true, filter: true },
  { prop: 'lane', name: 'Segment', size: 124, sortable: true, filter: true },
  { prop: 'solution', name: 'Solution', size: 190, sortable: true, filter: true },
  { prop: 'implementation', name: 'Implementation focus', size: 220, sortable: true, filter: true },
  { prop: 'handoff', name: 'Next handoff', size: 190, sortable: true, filter: true },
  { prop: 'goLiveDate', name: 'Go-live', size: 118, sortable: true },
];

export const SALES_ONBOARDING_SCENARIO = {
  id: 'sales-onboarding',
  cardPresentation: 'revenue-opportunity',
  useSwimlanes: false,
  colorScheme: 'light',
  layout: { cardRowHeight: 268, swimlaneWidth: 176, collapsedSwimlaneWidth: 44 },
  eyebrow: 'Revenue journey · Q3 customer cohort',
  title: 'Carry customer context from first fit to first value',
  description: 'Give sales, solution engineering, legal, and onboarding one accountable view of every customer promise, implementation handoff, and go-live date.',
  attention: {
    label: 'Implementation handoff needs an owner',
    detail: 'Implementation is at 5 of 4 accounts; Strategic carries 3 against its 2-account limit, and Lumen Energy’s security handoff has no named data owner.',
    tone: 'risk',
  },
  metrics: [
    { label: 'Open ARR', value: '$2.64M', tone: 'good' },
    { label: 'Implementation WIP', value: '5 / 4', tone: 'risk' },
    { label: 'In-flight Sep go-lives', value: '4', tone: 'attention' },
  ],
  workflowColumns: [
    { prop: 'qualified', name: 'Qualified', size: 333 },
    { prop: 'solution', name: 'Solution', size: 333, wipLimit: 4 },
    { prop: 'contract', name: 'Contract', size: 333, wipLimit: 3 },
    { prop: 'implementation', name: 'Implementation', size: 333, wipLimit: 4 },
    { prop: 'live', name: 'Live', size: 333 },
  ],
  swimlanes: [
    {
      id: 'strategic',
      title: 'Strategic accounts',
      collapsible: true,
      wipLimits: { implementation: 2 },
    },
    {
      id: 'growth',
      title: 'Growth accounts',
      collapsible: true,
      wipLimits: { solution: 2 },
    },
  ],
  wipBehavior: 'warn',
  columns,
  cards: [
    {
      id: 'REV-610',
      title: 'Atlas Health',
      account: 'Atlas Health',
      description: 'Confirm the clinical analytics use case and executive success measure.',
      status: 'qualified',
      lane: 'strategic',
      owner: 'Leah Morgan',
      assignees: ['Leah Morgan'],
      priority: 'High',
      label: 'Discovery',
      progress: 15,
      dueDate: 'Aug 12',
      order: 1000,
      arr: '$320k',
      arrValue: 320000,
      solution: 'Clinical analytics cloud',
      implementation: 'Discovery workshop',
      handoff: 'Account executive → Solutions',
      goLiveDate: '2026-10-19',
      context: '$320k ARR · Analytics · Go-live Oct 19',
    },
    {
      id: 'REV-611',
      title: 'Northstar Logistics',
      account: 'Northstar Logistics',
      description: 'Map dispatch exceptions into a measurable automation design.',
      status: 'solution',
      lane: 'strategic',
      owner: 'Noah Williams',
      assignees: ['Noah Williams'],
      priority: 'Medium',
      label: 'Solution design',
      progress: 35,
      dueDate: 'Aug 14',
      order: 1000,
      arr: '$240k',
      arrValue: 240000,
      solution: 'Workflow automation',
      implementation: 'Process mapping',
      handoff: 'Solutions → Security',
      goLiveDate: '2026-10-12',
      context: '$240k ARR · Automation · Go-live Oct 12',
    },
    {
      id: 'REV-612',
      title: 'Meridian Bank',
      account: 'Meridian Bank',
      description: 'Prove regional data controls before commercial approval.',
      status: 'solution',
      lane: 'strategic',
      owner: 'Priya Shah',
      assignees: ['Priya Shah'],
      priority: 'High',
      label: 'Security review',
      progress: 45,
      dueDate: 'Aug 18',
      order: 2000,
      arr: '$420k',
      arrValue: 420000,
      solution: 'Private analytics workspace',
      implementation: 'Residency architecture',
      handoff: 'Security → Procurement',
      goLiveDate: '2026-10-26',
      context: '$420k ARR · Private cloud · Go-live Oct 26',
    },
    {
      id: 'REV-613',
      title: 'Aurora Retail',
      account: 'Aurora Retail',
      description: 'Close order-form language and protect the agreed launch window.',
      status: 'contract',
      lane: 'strategic',
      owner: 'Leah Morgan',
      assignees: ['Leah Morgan'],
      priority: 'High',
      label: 'Commercial terms',
      progress: 60,
      dueDate: 'Aug 21',
      order: 1000,
      arr: '$180k',
      arrValue: 180000,
      solution: 'Commerce operations suite',
      implementation: 'Launch scope confirmed',
      handoff: 'Legal → Onboarding',
      goLiveDate: '2026-09-29',
      context: '$180k ARR · Commerce · Go-live Sep 29',
    },
    {
      id: 'REV-614',
      title: 'BluePeak Travel',
      account: 'BluePeak Travel',
      description: 'Reconcile booking history before the final migration rehearsal.',
      status: 'implementation',
      lane: 'strategic',
      owner: 'Maya Chen',
      assignees: ['Maya Chen', 'Jon Diaz', 'Priya Shah'],
      priority: 'High',
      label: 'Data migration',
      progress: 68,
      dueDate: 'Aug 28',
      order: 1000,
      arr: '$360k',
      arrValue: 360000,
      solution: 'Travel operations platform',
      implementation: 'Booking data migration',
      handoff: 'Data team → Customer admin',
      goLiveDate: '2026-09-08',
      context: '$360k ARR · Migration · Go-live Sep 8',
    },
    {
      id: 'REV-615',
      title: 'Cedar Bio',
      account: 'Cedar Bio',
      description: 'Configure role-based access for the research operations cohort.',
      status: 'implementation',
      lane: 'strategic',
      owner: 'Maya Chen',
      assignees: ['Maya Chen'],
      priority: 'Medium',
      label: 'Access design',
      progress: 52,
      dueDate: 'Sep 4',
      order: 2000,
      arr: '$280k',
      arrValue: 280000,
      solution: 'Research workspace',
      implementation: 'Roles and permissions',
      handoff: 'Onboarding → Customer IT',
      goLiveDate: '2026-09-22',
      context: '$280k ARR · Access · Go-live Sep 22',
    },
    {
      id: 'REV-616',
      title: 'Lumen Energy',
      account: 'Lumen Energy',
      description: 'Name the data owner required to approve the operational handoff.',
      status: 'implementation',
      lane: 'strategic',
      owner: 'Jon Diaz',
      assignees: ['Jon Diaz'],
      priority: 'Critical',
      label: 'Handoff blocked',
      progress: 38,
      dueDate: 'Sep 3',
      order: 3000,
      arr: '$225k',
      arrValue: 225000,
      solution: 'Field operations control',
      implementation: 'SCADA identity mapping',
      handoff: 'Security → Implementation',
      goLiveDate: '2026-10-02',
      context: '$225k ARR · Identity · Go-live Oct 2',
      risk: 'Security has not named a data owner, so implementation acceptance cannot begin.',
    },
    {
      id: 'REV-617',
      title: 'Redwood Foods',
      account: 'Redwood Foods',
      description: 'Track first-value adoption after a successful network rollout.',
      status: 'live',
      lane: 'strategic',
      owner: 'Sofia Reed',
      assignees: ['Sofia Reed'],
      priority: 'Low',
      label: 'Adoption',
      progress: 100,
      dueDate: 'Aug 11',
      order: 1000,
      arr: '$310k',
      arrValue: 310000,
      solution: 'Supply network control',
      implementation: 'Adoption measurement',
      handoff: 'Onboarding → Customer success',
      goLiveDate: '2026-08-04',
      context: '$310k ARR · Live · Value review Aug 11',
    },
    {
      id: 'REV-710',
      title: 'Nova Goods',
      account: 'Nova Goods',
      description: 'Validate the storefront workflow and buying committee.',
      status: 'qualified',
      lane: 'growth',
      owner: 'Caleb Young',
      assignees: ['Caleb Young'],
      priority: 'Medium',
      label: 'Qualification',
      progress: 10,
      dueDate: 'Aug 13',
      order: 1000,
      arr: '$84k',
      arrValue: 84000,
      solution: 'Storefront workflow',
      implementation: 'Fit validation',
      handoff: 'Account executive → Solutions',
      goLiveDate: '2026-10-20',
      context: '$84k ARR · Storefront · Go-live Oct 20',
    },
    {
      id: 'REV-711',
      title: 'Ember Market',
      account: 'Ember Market',
      description: 'Confirm inventory scale and the launch sponsor’s outcome.',
      status: 'qualified',
      lane: 'growth',
      owner: 'Caleb Young',
      assignees: ['Caleb Young'],
      priority: 'Medium',
      label: 'Discovery',
      progress: 18,
      dueDate: 'Aug 17',
      order: 2000,
      arr: '$72k',
      arrValue: 72000,
      solution: 'Inventory workspace',
      implementation: 'Scale assessment',
      handoff: 'Account executive → Solutions',
      goLiveDate: '2026-10-23',
      context: '$72k ARR · Inventory · Go-live Oct 23',
    },
    {
      id: 'REV-712',
      title: 'GreenCart',
      account: 'GreenCart',
      description: 'Finalize the catalog import path with the customer’s operations lead.',
      status: 'solution',
      lane: 'growth',
      owner: 'Iris Bell',
      assignees: ['Iris Bell'],
      priority: 'Medium',
      label: 'Solution design',
      progress: 42,
      dueDate: 'Aug 20',
      order: 1000,
      arr: '$96k',
      arrValue: 96000,
      solution: 'Catalog operations',
      implementation: 'Import design',
      handoff: 'Solutions → Commercial',
      goLiveDate: '2026-10-06',
      context: '$96k ARR · Catalog · Go-live Oct 6',
    },
    {
      id: 'REV-713',
      title: 'Orchard Labs',
      account: 'Orchard Labs',
      description: 'Collect the final signature and confirm the onboarding sponsor.',
      status: 'contract',
      lane: 'growth',
      owner: 'Caleb Young',
      assignees: ['Caleb Young'],
      priority: 'Medium',
      label: 'Signature',
      progress: 72,
      dueDate: 'Aug 24',
      order: 1000,
      arr: '$120k',
      arrValue: 120000,
      solution: 'Team analytics',
      implementation: 'Sponsor confirmed',
      handoff: 'Commercial → Onboarding',
      goLiveDate: '2026-09-30',
      context: '$120k ARR · Analytics · Go-live Sep 30',
    },
    {
      id: 'REV-714',
      title: 'SwiftShip',
      account: 'SwiftShip',
      description: 'Complete carrier sandbox verification before training starts.',
      status: 'implementation',
      lane: 'growth',
      owner: 'Jon Diaz',
      assignees: ['Jon Diaz'],
      priority: 'High',
      label: 'Integration',
      progress: 76,
      dueDate: 'Sep 2',
      order: 1000,
      arr: '$108k',
      arrValue: 108000,
      solution: 'Carrier integration hub',
      implementation: 'Sandbox verification',
      handoff: 'Integration → Enablement',
      goLiveDate: '2026-09-11',
      context: '$108k ARR · Integration · Go-live Sep 11',
    },
    {
      id: 'REV-715',
      title: 'CloudNine Media',
      account: 'CloudNine Media',
      description: 'Finish identity mapping and schedule the admin rehearsal.',
      status: 'implementation',
      lane: 'growth',
      owner: 'Nora Reed',
      assignees: ['Nora Reed'],
      priority: 'Medium',
      label: 'Enablement',
      progress: 58,
      dueDate: 'Sep 7',
      order: 2000,
      arr: '$132k',
      arrValue: 132000,
      solution: 'Campaign workspace',
      implementation: 'Admin enablement',
      handoff: 'Enablement → Customer admin',
      goLiveDate: '2026-09-24',
      context: '$132k ARR · Enablement · Go-live Sep 24',
    },
    {
      id: 'REV-716',
      title: 'Brightline Studio',
      account: 'Brightline Studio',
      description: 'Review adoption signals after the team’s first live campaign.',
      status: 'live',
      lane: 'growth',
      owner: 'Sofia Reed',
      assignees: ['Sofia Reed'],
      priority: 'Low',
      label: 'First value',
      progress: 100,
      dueDate: 'Aug 14',
      order: 1000,
      arr: '$90k',
      arrValue: 90000,
      solution: 'Creative operations',
      implementation: 'Adoption measurement',
      handoff: 'Onboarding → Customer success',
      goLiveDate: '2026-08-05',
      context: '$90k ARR · Live · Value review Aug 14',
    },
    {
      id: 'REV-717',
      title: 'Harlow Commerce',
      account: 'Harlow Commerce',
      description: 'Confirm support ownership after the successful catalog launch.',
      status: 'live',
      lane: 'growth',
      owner: 'Sofia Reed',
      assignees: ['Sofia Reed'],
      priority: 'Low',
      label: 'Transitioned',
      progress: 100,
      dueDate: 'Aug 18',
      order: 2000,
      arr: '$114k',
      arrValue: 114000,
      solution: 'Commerce catalog',
      implementation: 'Success transition',
      handoff: 'Onboarding → Customer success',
      goLiveDate: '2026-08-06',
      context: '$114k ARR · Live · Value review Aug 18',
    },
  ],
} satisfies KanbanUseCaseScenario;
