import type { ColumnRegular } from '@revolist/revogrid';
import type { KanbanUseCaseScenario } from '../kanban-use-case-model';

const columns: ColumnRegular[] = [
  { prop: 'id', name: 'Case', size: 108, sortable: true, filter: true },
  { prop: 'title', name: 'Customer issue', size: 280, sortable: true, filter: true },
  { prop: 'account', name: 'Account', size: 156, sortable: true, filter: true },
  { prop: 'owner', name: 'Case owner', size: 138, sortable: true, filter: true },
  { prop: 'status', name: 'Stage', size: 150, sortable: true, filter: true },
  { prop: 'lane', name: 'Support team', size: 138, sortable: true, filter: true },
  { prop: 'severity', name: 'Severity', size: 92, sortable: true, filter: true },
  { prop: 'slaState', name: 'SLA', size: 116, sortable: true, filter: true },
  { prop: 'channel', name: 'Channel', size: 104, sortable: true, filter: true },
  { prop: 'escalation', name: 'Escalation', size: 164, sortable: true, filter: true },
  { prop: 'dueDate', name: 'Next update', size: 136, sortable: true },
];

export const SUPPORT_OPERATIONS_SCENARIO = {
  id: 'support-operations',
  cardPresentation: 'support-ticket',
  useSwimlanes: true,
  swimlaneLayout: 'top',
  colorScheme: 'dark',
  layout: { cardRowHeight: 250, swimlaneWidth: 170, collapsedSwimlaneWidth: 44 },
  eyebrow: 'Support operations · Friday coverage',
  title: 'Every customer knows what happens next',
  description: 'Bring urgent incidents, customer replies, specialist handoffs, and resolved cases into one service view so support leaders can protect SLAs without losing the human story behind each ticket.',
  attention: {
    label: 'Investigation capacity needs action',
    detail: 'Investigating is at 5 of 4 cases; Enterprise carries 3 against its 2-case limit while RetailCloud has 42 minutes left on its P1 resolution SLA.',
    tone: 'risk',
  },
  metrics: [
    { label: 'Cases within SLA', value: '92%', tone: 'attention' },
    { label: 'Investigation WIP', value: '5 / 4', tone: 'risk' },
    { label: 'Median first response', value: '8 min', tone: 'good' },
  ],
  workflowColumns: [
    { prop: 'new', name: 'New', size: 288 },
    { prop: 'triage', name: 'Triage', size: 288, wipLimit: 3 },
    { prop: 'investigating', name: 'Investigating', size: 288, wipLimit: 4 },
    { prop: 'waiting-on-customer', name: 'Customer reply', size: 288, wipLimit: 4 },
    { prop: 'resolved', name: 'Resolved', size: 288 },
  ],
  swimlanes: [
    {
      id: 'enterprise',
      title: 'Enterprise support',
      collapsible: true,
      wipLimits: { investigating: 2 },
    },
    {
      id: 'digital',
      title: 'Digital support',
      collapsible: true,
      wipLimits: { triage: 2 },
    },
  ],
  wipBehavior: 'warn',
  columns,
  cards: [
    {
      id: 'SO-8434',
      title: 'Confirm EU data residency coverage',
      description: 'Clarify which analytics events remain inside the Frankfurt region.',
      status: 'new',
      lane: 'enterprise',
      owner: 'Mina Park',
      assignees: ['Mina Park'],
      priority: 'Medium',
      label: 'P3 · Guidance',
      progress: 5,
      dueDate: 'Aug 7 · 12:20',
      order: 1000,
      account: 'Meridian Bank',
      severity: 'P3',
      slaTarget: '4h first response',
      slaState: '3h 18m left',
      channel: 'Portal',
      escalation: 'Privacy specialist',
      handoff: 'Frontline → Privacy',
      context: 'Meridian Bank · 3h 18m SLA · Portal',
    },
    {
      id: 'SO-8422',
      title: 'Mobile webhooks arriving out of order',
      description: 'Checkout updates appear after fulfillment events in the mobile feed.',
      status: 'new',
      lane: 'enterprise',
      owner: 'Owen Brooks',
      assignees: ['Owen Brooks', 'Nadia Flores'],
      priority: 'High',
      label: 'P2 · Integration',
      progress: 10,
      dueDate: 'Aug 7 · 12:05',
      order: 2000,
      account: 'BluePeak Travel',
      severity: 'P2',
      slaTarget: '2h first response',
      slaState: '1h 06m left',
      channel: 'Email',
      escalation: 'API support',
      handoff: 'Frontline → API',
      context: 'BluePeak Travel · 1h 06m SLA · Email',
    },
    {
      id: 'SO-8425',
      title: 'Invoice total differs from usage export',
      description: 'Reconcile two metered seats before the customer closes its month.',
      status: 'triage',
      lane: 'enterprise',
      owner: 'Mina Park',
      assignees: ['Mina Park', 'Theo Grant'],
      priority: 'High',
      label: 'P2 · Billing',
      progress: 20,
      dueDate: 'Aug 7 · 12:45',
      order: 1000,
      account: 'Harlow Marketplace',
      severity: 'P2',
      slaTarget: '4h resolution plan',
      slaState: '2h 12m left',
      channel: 'Portal',
      escalation: 'Billing ops',
      handoff: 'Support → Billing ops',
      context: 'Harlow Marketplace · 2h 12m SLA · Portal',
    },
    {
      id: 'SO-8421',
      title: 'Checkout callbacks failing in EU',
      description: 'Payment confirmations are timing out for two production regions.',
      status: 'investigating',
      lane: 'enterprise',
      owner: 'Nadia Flores',
      assignees: ['Nadia Flores', 'Ibrahim Khan', 'Owen Brooks'],
      priority: 'Critical',
      label: 'P1 · Incident',
      progress: 55,
      dueDate: 'Aug 7 · 11:40',
      order: 1000,
      account: 'RetailCloud',
      severity: 'P1',
      slaTarget: '2h resolution',
      slaState: '42m left',
      channel: 'Phone',
      escalation: 'Incident commander',
      handoff: 'Enterprise → Payments SRE',
      context: 'RetailCloud · 42m SLA · Phone bridge',
      risk: 'The P1 resolution SLA has 42 minutes left; Payments SRE is tracing regional callback failures.',
    },
    {
      id: 'SO-8427',
      title: 'SSO loops after idle timeout',
      description: 'Clinicians are sent back to the identity provider after re-authentication.',
      status: 'investigating',
      lane: 'enterprise',
      owner: 'Ibrahim Khan',
      assignees: ['Ibrahim Khan', 'Mina Park'],
      priority: 'High',
      label: 'P2 · Identity',
      progress: 45,
      dueDate: 'Aug 7 · 13:10',
      order: 2000,
      account: 'Atlas Health',
      severity: 'P2',
      slaTarget: '4h mitigation',
      slaState: '2h 28m left',
      channel: 'Slack Connect',
      escalation: 'Identity engineering',
      handoff: 'Enterprise → Identity',
      context: 'Atlas Health · 2h 28m SLA · Slack',
      risk: 'A safe session-cookie rollback needs Identity engineering approval.',
    },
    {
      id: 'SO-8430',
      title: 'Audit export stalls at 90 percent',
      description: 'The quarterly evidence export stops when attachments are included.',
      status: 'investigating',
      lane: 'enterprise',
      owner: 'Owen Brooks',
      assignees: ['Owen Brooks', 'Nadia Flores'],
      priority: 'High',
      label: 'P2 · Compliance',
      progress: 35,
      dueDate: 'Aug 7 · 14:00',
      order: 3000,
      account: 'Northstar Finance',
      severity: 'P2',
      slaTarget: '6h resolution plan',
      slaState: '3h 06m left',
      channel: 'Phone',
      escalation: 'Data platform',
      handoff: 'Enterprise → Data platform',
      context: 'Northstar Finance · 3h 06m SLA · Phone',
    },
    {
      id: 'SO-8411',
      title: 'Validate outbound IP allowlist',
      description: 'Confirm the customer firewall permits the new notification range.',
      status: 'waiting-on-customer',
      lane: 'enterprise',
      owner: 'Mina Park',
      assignees: ['Mina Park', 'Owen Brooks'],
      priority: 'Medium',
      label: 'P3 · Network',
      progress: 70,
      dueDate: 'Aug 7 · 15:00',
      order: 1000,
      account: 'Brightline Energy',
      severity: 'P3',
      slaTarget: 'Paused for customer',
      slaState: 'Clock paused',
      channel: 'Email',
      escalation: 'Customer network',
      handoff: 'Network → Customer admin',
      context: 'Brightline Energy · SLA paused · Email',
    },
    {
      id: 'SO-8398',
      title: 'Remove duplicate workspace provisioning',
      description: 'Cleaned the duplicate tenant and confirmed every member retained access.',
      status: 'resolved',
      lane: 'enterprise',
      owner: 'Nadia Flores',
      assignees: ['Nadia Flores', 'Ibrahim Khan'],
      priority: 'Low',
      label: 'P3 · Resolved',
      progress: 100,
      dueDate: 'Aug 7 · 09:15',
      order: 1000,
      account: 'CloudNine Media',
      severity: 'P3',
      slaTarget: '8h resolution',
      slaState: 'Met · 2h early',
      channel: 'Portal',
      escalation: 'Provisioning',
      handoff: 'Provisioning → Customer success',
      context: 'CloudNine Media · SLA met · Portal',
    },
    {
      id: 'SO-8429',
      title: 'Theme publish remains queued',
      description: 'A storefront update has shown “publishing” since the morning deploy.',
      status: 'new',
      lane: 'digital',
      owner: 'Sofia Reed',
      assignees: ['Sofia Reed'],
      priority: 'Medium',
      label: 'P3 · Storefront',
      progress: 5,
      dueDate: 'Aug 7 · 12:35',
      order: 1000,
      account: 'Luma Store',
      severity: 'P3',
      slaTarget: '2h first response',
      slaState: '1h 44m left',
      channel: 'Chat',
      escalation: 'Theme platform',
      handoff: 'Chat → Theme platform',
      context: 'Luma Store · 1h 44m SLA · Chat',
    },
    {
      id: 'SO-8431',
      title: 'Password reset email not received',
      description: 'Check suppression and delivery history before asking the user to retry.',
      status: 'triage',
      lane: 'digital',
      owner: 'Caleb Young',
      assignees: ['Caleb Young', 'Sofia Reed'],
      priority: 'Medium',
      label: 'P3 · Access',
      progress: 20,
      dueDate: 'Aug 7 · 12:50',
      order: 1000,
      account: 'Orchard Labs',
      severity: 'P3',
      slaTarget: '4h resolution',
      slaState: '2h 52m left',
      channel: 'Chat',
      escalation: 'Messaging',
      handoff: 'Chat → Messaging',
      context: 'Orchard Labs · 2h 52m SLA · Chat',
    },
    {
      id: 'SO-8432',
      title: 'SKU import rejects valid rows',
      description: 'Compare the customer CSV locale with the current decimal parser.',
      status: 'triage',
      lane: 'digital',
      owner: 'Jules Martin',
      assignees: ['Jules Martin', 'Caleb Young'],
      priority: 'High',
      label: 'P2 · Catalog',
      progress: 25,
      dueDate: 'Aug 7 · 12:15',
      order: 2000,
      account: 'GreenCart',
      severity: 'P2',
      slaTarget: '2h first response',
      slaState: '58m left',
      channel: 'Portal',
      escalation: 'Catalog engineering',
      handoff: 'Support → Catalog',
      context: 'GreenCart · 58m SLA · Portal',
      risk: 'A bulk catalog launch is blocked while the locale parsing defect is triaged.',
    },
    {
      id: 'SO-8420',
      title: 'Label purchase timing out',
      description: 'Carrier quotes load, but the final purchase request exceeds ten seconds.',
      status: 'investigating',
      lane: 'digital',
      owner: 'Jules Martin',
      assignees: ['Jules Martin', 'Sofia Reed'],
      priority: 'High',
      label: 'P2 · Shipping',
      progress: 60,
      dueDate: 'Aug 7 · 13:30',
      order: 1000,
      account: 'SwiftShip',
      severity: 'P2',
      slaTarget: '6h resolution',
      slaState: '3h 38m left',
      channel: 'Chat',
      escalation: 'Carrier integrations',
      handoff: 'Digital → Carrier team',
      context: 'SwiftShip · 3h 38m SLA · Chat',
    },
    {
      id: 'SO-8424',
      title: 'Card reader disconnects after sleep',
      description: 'Reproduce the Bluetooth reconnect path on the latest tablet release.',
      status: 'investigating',
      lane: 'digital',
      owner: 'Sofia Reed',
      assignees: ['Sofia Reed', 'Caleb Young'],
      priority: 'Medium',
      label: 'P3 · Hardware',
      progress: 50,
      dueDate: 'Aug 7 · 15:20',
      order: 2000,
      account: 'Ember Cafe',
      severity: 'P3',
      slaTarget: '8h resolution',
      slaState: '5h 24m left',
      channel: 'Phone',
      escalation: 'Device support',
      handoff: 'Digital → Device lab',
      context: 'Ember Cafe · 5h 24m SLA · Phone',
    },
    {
      id: 'SO-8407',
      title: 'Collect Safari checkout trace',
      description: 'Await the browser recording needed to isolate a one-customer redirect loop.',
      status: 'waiting-on-customer',
      lane: 'digital',
      owner: 'Caleb Young',
      assignees: ['Caleb Young', 'Jules Martin'],
      priority: 'Medium',
      label: 'P3 · Browser',
      progress: 65,
      dueDate: 'Aug 7 · 16:00',
      order: 1000,
      account: 'Nova Goods',
      severity: 'P3',
      slaTarget: 'Paused for customer',
      slaState: 'Clock paused',
      channel: 'Email',
      escalation: 'Customer developer',
      handoff: 'Web support → Customer dev',
      context: 'Nova Goods · SLA paused · Email',
    },
    {
      id: 'SO-8415',
      title: 'Confirm tax discrepancy example',
      description: 'Waiting for the order ID that shows the expected and charged tax.',
      status: 'waiting-on-customer',
      lane: 'digital',
      owner: 'Jules Martin',
      assignees: ['Jules Martin', 'Sofia Reed'],
      priority: 'Low',
      label: 'P4 · Tax',
      progress: 75,
      dueDate: 'Aug 8 · 10:00',
      order: 2000,
      account: 'Woven Home',
      severity: 'P4',
      slaTarget: 'Paused for customer',
      slaState: 'Clock paused',
      channel: 'Portal',
      escalation: 'Customer finance',
      handoff: 'Tax support → Customer finance',
      context: 'Woven Home · SLA paused · Portal',
    },
    {
      id: 'SO-8392',
      title: 'Restore catalog sync schedule',
      description: 'Reconnected the catalog feed and verified two healthy scheduled runs.',
      status: 'resolved',
      lane: 'digital',
      owner: 'Caleb Young',
      assignees: ['Caleb Young', 'Jules Martin'],
      priority: 'Low',
      label: 'P4 · Resolved',
      progress: 100,
      dueDate: 'Aug 7 · 08:42',
      order: 1000,
      account: 'Cedar & Co',
      severity: 'P4',
      slaTarget: '12h resolution',
      slaState: 'Met · 4h early',
      channel: 'Monitoring',
      escalation: 'Catalog operations',
      handoff: 'Catalog ops → Customer',
      context: 'Cedar & Co · SLA met · Monitoring',
    },
  ],
} satisfies KanbanUseCaseScenario;
