import type { ColumnRegular } from '@revolist/revogrid';
import type { KanbanUseCaseScenario } from '../kanban-use-case-model';

const columns: ColumnRegular[] = [
  { prop: 'id', name: 'Quality case', size: 116, sortable: true, filter: true },
  { prop: 'title', name: 'Defect or improvement', size: 280, sortable: true, filter: true },
  { prop: 'workOrder', name: 'Work order', size: 116, sortable: true, filter: true },
  { prop: 'owner', name: 'Owner', size: 136, sortable: true, filter: true },
  { prop: 'status', name: 'Quality stage', size: 164, sortable: true, filter: true },
  { prop: 'lane', name: 'Production line', size: 132, sortable: true, filter: true },
  { prop: 'severity', name: 'Severity', size: 98, sortable: true, filter: true },
  { prop: 'machine', name: 'Machine / station', size: 156, sortable: true, filter: true },
  { prop: 'material', name: 'Material', size: 164, sortable: true, filter: true },
  { prop: 'lot', name: 'Lot', size: 142, sortable: true, filter: true },
  { prop: 'inspection', name: 'Inspection', size: 148, sortable: true, filter: true },
  { prop: 'dueDate', name: 'Next review', size: 136, sortable: true },
];

export const QUALITY_MANUFACTURING_SCENARIO = {
  id: 'quality-manufacturing',
  cardPresentation: 'quality-inspection',
  headerIcons: {
    detected: 'triangle-exclamation',
    containment: 'shield-halved',
    capa: 'gears',
    verification: 'check-circle',
    closed: 'lock',
  },
  useSwimlanes: true,
  swimlaneLayout: 'column',
  colorScheme: 'dark',
  layout: { cardRowHeight: 265, swimlaneWidth: 246, collapsedSwimlaneWidth: 56 },
  eyebrow: 'Plant quality · Morning review',
  title: 'Protect the customer without stopping the whole plant',
  description: 'Connect defects to the exact work order, machine, material lot, inspection, and next owner so operators can contain risk quickly and quality teams can prove the fix really worked.',
  attention: {
    label: 'Material hold needs a decision',
    detail: 'Containment is at 4 of 3 cases; Power Modules carries 3 against its 2-case limit while capacitor lot CAP-260805-17 puts 1,240 units on hold.',
    tone: 'risk',
  },
  metrics: [
    { label: 'First-pass yield', value: '96.8%', tone: 'attention' },
    { label: 'Containment WIP', value: '4 / 3', tone: 'risk' },
    { label: 'Units on material hold', value: '1,240', tone: 'risk' },
  ],
  workflowColumns: [
    { prop: 'detected', name: 'Detected', size: 285 },
    { prop: 'containment', name: 'Containment', size: 285, wipLimit: 3 },
    { prop: 'capa', name: 'Root cause & CAPA', size: 285, wipLimit: 4 },
    { prop: 'verification', name: 'Verification', size: 285, wipLimit: 3 },
    { prop: 'closed', name: 'Closed', size: 285 },
  ],
  swimlanes: [
    {
      id: 'line-a',
      title: 'Line A · Enclosure assembly',
      collapsible: true,
      wipLimits: { containment: 3, capa: 2 },
    },
    {
      id: 'line-b',
      title: 'Line B · Power modules',
      collapsible: true,
      wipLimits: { containment: 2, capa: 4 },
    },
  ],
  wipBehavior: 'warn',
  columns,
  cards: [
    {
      id: 'QM-7312',
      title: 'Door seam gap above drawing limit',
      description: 'Three first-off enclosures exceed the 1.2 mm flushness tolerance.',
      status: 'detected',
      lane: 'line-a',
      owner: 'Lena Ortiz',
      assignees: ['Lena Ortiz', 'Marcus Lee'],
      priority: 'High',
      label: 'Major · Dimensional',
      progress: 10,
      dueDate: 'Aug 7 · 12:30',
      order: 1000,
      workOrder: 'WO-48621',
      defect: 'Seam flushness above 1.2 mm',
      severity: 'Major',
      machine: 'Brake press BP-04',
      material: '304 SS door blank',
      lot: 'SS-260807-04',
      inspection: 'First-off gauge',
      handoff: 'Line inspector → Process engineer',
      unitsHeld: 24,
      context: 'WO-48621 · SS-260807-04 · First-off gauge',
    },
    {
      id: 'QM-7308',
      title: 'Powder coat peels at lower hinge',
      description: 'Contain the affected rack while the team checks wash-stage chemistry.',
      status: 'containment',
      lane: 'line-a',
      owner: 'Karim Haddad',
      assignees: ['Karim Haddad', 'Lena Ortiz', 'Sonia Patel'],
      priority: 'High',
      label: 'Major · Surface',
      progress: 35,
      dueDate: 'Aug 7 · 12:00',
      order: 1000,
      workOrder: 'WO-48593',
      defect: 'Adhesion loss after cross-hatch test',
      severity: 'Major',
      machine: 'Coating booth CB-02',
      material: 'Slate powder coat',
      lot: 'PC-260806-11',
      inspection: 'Cross-hatch test',
      handoff: 'Line quality → Finishing engineer',
      unitsHeld: 360,
      context: 'WO-48593 · PC-260806-11 · 360 held',
      risk: 'The rack remains quarantined until pretreatment bath samples clear the lab.',
    },
    {
      id: 'QM-7299',
      title: 'Hinge fastener torque drifts high',
      description: 'Confirm whether the rundown controller calibration caused thread damage.',
      status: 'capa',
      lane: 'line-a',
      owner: 'Marcus Lee',
      assignees: ['Marcus Lee', 'Lena Ortiz'],
      priority: 'High',
      label: 'Major · Assembly',
      progress: 62,
      dueDate: 'Aug 7 · 14:00',
      order: 1000,
      workOrder: 'WO-48562',
      defect: 'Torque exceeds 11 Nm upper limit',
      severity: 'Major',
      machine: 'Torque tool DC-17',
      material: 'M6 hinge fastener',
      lot: 'FS-260804-22',
      inspection: 'Torque audit',
      handoff: 'Maintenance → Process engineering',
      unitsHeld: 84,
      context: 'WO-48562 · DC-17 · Torque audit',
    },
    {
      id: 'QM-7304',
      title: 'Traceability label lifts after wash',
      description: 'Validate the new label stock and revise surface-prep instructions.',
      status: 'capa',
      lane: 'line-a',
      owner: 'Sonia Patel',
      assignees: ['Sonia Patel', 'Karim Haddad'],
      priority: 'Medium',
      label: 'Minor · Traceability',
      progress: 55,
      dueDate: 'Aug 8 · 10:00',
      order: 2000,
      workOrder: 'WO-48578',
      defect: 'Label edge lift greater than 3 mm',
      severity: 'Minor',
      machine: 'Label printer LB-03',
      material: 'PET label stock',
      lot: 'LB-260805-09',
      inspection: 'Wash-cycle peel test',
      handoff: 'Supplier quality → Line quality',
      unitsHeld: 120,
      context: 'WO-48578 · LB-260805-09 · Peel test',
    },
    {
      id: 'QM-7287',
      title: 'Verify revised weld fixture locator',
      description: 'Run thirty enclosures and confirm the locator keeps the frame square.',
      status: 'verification',
      lane: 'line-a',
      owner: 'Lena Ortiz',
      assignees: ['Lena Ortiz', 'Marcus Lee'],
      priority: 'Medium',
      label: 'Major · Verification',
      progress: 82,
      dueDate: 'Aug 7 · 15:30',
      order: 1000,
      workOrder: 'WO-48496',
      defect: 'Frame diagonal exceeded 2 mm',
      severity: 'Major',
      machine: 'Weld robot WB-01',
      material: 'Frame subassembly',
      lot: 'FR-260801-15',
      inspection: '30-piece capability',
      handoff: 'Process engineer → Quality engineer',
      unitsHeld: 0,
      context: 'WO-48496 · WB-01 · 30-piece study',
    },
    {
      id: 'QM-7294',
      title: 'Confirm punch profile after die change',
      description: 'Complete first-off and last-off checks before releasing the replacement die.',
      status: 'verification',
      lane: 'line-a',
      owner: 'Karim Haddad',
      assignees: ['Karim Haddad', 'Sonia Patel'],
      priority: 'Medium',
      label: 'Minor · Verification',
      progress: 90,
      dueDate: 'Aug 7 · 13:40',
      order: 2000,
      workOrder: 'WO-48533',
      defect: 'Vent profile burr after die wear',
      severity: 'Minor',
      machine: 'Punch press PP-06',
      material: 'Galvanized side panel',
      lot: 'GI-260803-07',
      inspection: 'Profile comparator',
      handoff: 'Toolroom → Line quality',
      unitsHeld: 0,
      context: 'WO-48533 · PP-06 · Profile check',
    },
    {
      id: 'QM-7260',
      title: 'Restore door seal compression',
      description: 'Closed after three shifts held compression and leak-test results.',
      status: 'closed',
      lane: 'line-a',
      owner: 'Sonia Patel',
      assignees: ['Sonia Patel', 'Lena Ortiz'],
      priority: 'Low',
      label: 'Major · Closed',
      progress: 100,
      dueDate: 'Aug 7 · 09:10',
      order: 1000,
      workOrder: 'WO-48388',
      defect: 'Seal compression below 28 percent',
      severity: 'Major',
      machine: 'Seal press SP-02',
      material: 'EPDM door seal',
      lot: 'EP-260729-08',
      inspection: 'Leak and compression test',
      handoff: 'Quality engineer → Production owner',
      unitsHeld: 0,
      context: 'WO-48388 · EP-260729-08 · 3 shifts clear',
    },
    {
      id: 'QM-7272',
      title: 'Eliminate sharp edge at cable opening',
      description: 'Closed after deburr brush replacement and layered process audit.',
      status: 'closed',
      lane: 'line-a',
      owner: 'Marcus Lee',
      assignees: ['Marcus Lee', 'Karim Haddad'],
      priority: 'Low',
      label: 'Critical · Closed',
      progress: 100,
      dueDate: 'Aug 7 · 08:45',
      order: 2000,
      workOrder: 'WO-48421',
      defect: 'Sharp edge at cable knockout',
      severity: 'Critical',
      machine: 'Deburr cell DB-05',
      material: 'Enclosure back panel',
      lot: 'BP-260730-12',
      inspection: '100% tactile check',
      handoff: 'Safety quality → Production owner',
      unitsHeld: 0,
      context: 'WO-48421 · DB-05 · Audit passed',
    },
    {
      id: 'QM-7318',
      title: 'Connector pins bent at unload',
      description: 'Inspect the transfer nest before the next power-module batch starts.',
      status: 'detected',
      lane: 'line-b',
      owner: 'Diego Ramos',
      assignees: ['Diego Ramos', 'Mei Tan'],
      priority: 'High',
      label: 'Major · Component',
      progress: 10,
      dueDate: 'Aug 7 · 11:50',
      order: 1000,
      workOrder: 'WO-48642',
      defect: 'Connector pin coplanarity above 0.4 mm',
      severity: 'Major',
      machine: 'Insertion cell CT-08',
      material: '24-pin connector',
      lot: 'CN-260807-03',
      inspection: 'Vision coplanarity',
      handoff: 'EOL inspector → Automation tech',
      unitsHeld: 48,
      context: 'WO-48642 · CN-260807-03 · Vision check',
    },
    {
      id: 'QM-7315',
      title: 'Incoming capacitors fail ESR limit',
      description: 'Hold the exposed build and decide whether to sort or return the supplier lot.',
      status: 'containment',
      lane: 'line-b',
      owner: 'Mei Tan',
      assignees: ['Mei Tan', 'Avery Cole', 'Diego Ramos'],
      priority: 'Critical',
      label: 'Critical · Material',
      progress: 38,
      dueDate: 'Aug 7 · 11:30',
      order: 1000,
      workOrder: 'WO-48635',
      defect: 'Equivalent series resistance above 42 mΩ',
      severity: 'Critical',
      machine: 'Incoming LCR bench',
      material: '680 µF capacitor',
      lot: 'CAP-260805-17',
      inspection: 'Incoming AQL',
      handoff: 'Incoming quality → Supplier quality',
      unitsHeld: 1240,
      context: 'WO-48635 · CAP-260805-17 · 1,240 held',
      risk: 'The supplier lot spans 1,240 queued modules; production needs a sort-or-return decision by 11:30.',
    },
    {
      id: 'QM-7310',
      title: 'Potting voids visible in X-ray',
      description: 'Quarantine the pour window and confirm mixer pressure and resin temperature.',
      status: 'containment',
      lane: 'line-b',
      owner: 'Avery Cole',
      assignees: ['Avery Cole', 'Mei Tan'],
      priority: 'High',
      label: 'Major · Process',
      progress: 42,
      dueDate: 'Aug 7 · 12:10',
      order: 2000,
      workOrder: 'WO-48608',
      defect: 'Internal void area above 5 percent',
      severity: 'Major',
      machine: 'Potting cell PC-03',
      material: 'Thermoset resin',
      lot: 'RS-260806-14',
      inspection: 'X-ray sample',
      handoff: 'X-ray lab → Process engineering',
      unitsHeld: 96,
      context: 'WO-48608 · RS-260806-14 · X-ray hold',
      risk: 'The next pour window cannot start until mixer pressure is verified.',
    },
    {
      id: 'QM-7317',
      title: 'Firmware checksum mismatch at EOL',
      description: 'Stop release, preserve flash logs, and identify the affected image bundle.',
      status: 'containment',
      lane: 'line-b',
      owner: 'Diego Ramos',
      assignees: ['Diego Ramos', 'Noah Kim', 'Mei Tan'],
      priority: 'Critical',
      label: 'Critical · Traceability',
      progress: 45,
      dueDate: 'Aug 7 · 12:25',
      order: 3000,
      workOrder: 'WO-48639',
      defect: 'Loaded image checksum differs from traveler',
      severity: 'Critical',
      machine: 'Flash station FS-12',
      material: 'Firmware bundle 26.8.7',
      lot: 'FW-260807-02',
      inspection: 'EOL checksum',
      handoff: 'Line quality → Firmware release',
      unitsHeld: 240,
      context: 'WO-48639 · FW-260807-02 · 240 held',
      risk: 'Release is blocked until Firmware confirms whether the signed image bundle changed.',
    },
    {
      id: 'QM-7301',
      title: 'Prevent solder splash near busbar',
      description: 'Trial the revised shield and update the selective-solder recipe.',
      status: 'capa',
      lane: 'line-b',
      owner: 'Noah Kim',
      assignees: ['Noah Kim', 'Diego Ramos'],
      priority: 'High',
      label: 'Critical · Electrical',
      progress: 68,
      dueDate: 'Aug 7 · 15:00',
      order: 1000,
      workOrder: 'WO-48570',
      defect: 'Conductive splash inside 3 mm keepout',
      severity: 'Critical',
      machine: 'Selective solder SS-04',
      material: 'Lead-free solder wire',
      lot: 'SW-260804-19',
      inspection: 'AOI keepout check',
      handoff: 'Electrical quality → Process engineer',
      unitsHeld: 72,
      context: 'WO-48570 · SS-04 · Shield trial',
    },
    {
      id: 'QM-7289',
      title: 'Verify thermal-interface dispense fix',
      description: 'Complete thermal cycling and compare hotspot spread with the approved sample.',
      status: 'verification',
      lane: 'line-b',
      owner: 'Avery Cole',
      assignees: ['Avery Cole', 'Noah Kim'],
      priority: 'Medium',
      label: 'Major · Verification',
      progress: 88,
      dueDate: 'Aug 8 · 09:30',
      order: 1000,
      workOrder: 'WO-48518',
      defect: 'Thermal-interface coverage below 92 percent',
      severity: 'Major',
      machine: 'Dispense cell DS-06',
      material: 'Thermal interface gel',
      lot: 'TG-260802-05',
      inspection: 'Thermal-cycle test',
      handoff: 'Reliability lab → Quality engineer',
      unitsHeld: 0,
      context: 'WO-48518 · TG-260802-05 · Cycle 18/20',
    },
    {
      id: 'QM-7268',
      title: 'Correct polarity scan false rejects',
      description: 'Closed after lighting adjustment and five clean production batches.',
      status: 'closed',
      lane: 'line-b',
      owner: 'Diego Ramos',
      assignees: ['Diego Ramos', 'Mei Tan'],
      priority: 'Low',
      label: 'Minor · Closed',
      progress: 100,
      dueDate: 'Aug 7 · 09:25',
      order: 1000,
      workOrder: 'WO-48405',
      defect: 'Vision false reject at capacitor polarity',
      severity: 'Minor',
      machine: 'AOI station VI-09',
      material: 'Power control PCB',
      lot: 'PCB-260730-21',
      inspection: 'AOI challenge set',
      handoff: 'Automation tech → Production owner',
      unitsHeld: 0,
      context: 'WO-48405 · VI-09 · 5 batches clear',
    },
    {
      id: 'QM-7276',
      title: 'Remove fan vibration at final test',
      description: 'Closed after supplier hub runout limits and receiving checks were tightened.',
      status: 'closed',
      lane: 'line-b',
      owner: 'Mei Tan',
      assignees: ['Mei Tan', 'Avery Cole'],
      priority: 'Low',
      label: 'Major · Closed',
      progress: 100,
      dueDate: 'Aug 7 · 08:55',
      order: 2000,
      workOrder: 'WO-48440',
      defect: 'Fan vibration above 3.5 mm/s RMS',
      severity: 'Major',
      machine: 'EOL vibration rig',
      material: 'Cooling fan assembly',
      lot: 'FN-260731-10',
      inspection: 'Vibration spectrum',
      handoff: 'Supplier quality → Production owner',
      unitsHeld: 0,
      context: 'WO-48440 · FN-260731-10 · Audit closed',
    },
  ],
} satisfies KanbanUseCaseScenario;
