import type { ColumnRegular } from '@revolist/revogrid';
import type { KanbanSwimlaneTemplate } from '@revolist/revogrid-pro';
import type { KanbanUseCaseScenario } from '../kanban-use-case-model';

const productSwimlaneTemplate: KanbanSwimlaneTemplate = (h, context) => h('div', {
  class: 'product-delivery-workstream',
}, [
  h('span', { class: 'product-delivery-workstream__mark', 'aria-hidden': 'true' }, ''),
  h('span', { class: 'product-delivery-workstream__copy' }, [
    h('small', {}, 'WORKSTREAM'),
    h('strong', {}, context.swimlane.title),
  ]),
  h('span', { class: 'product-delivery-workstream__count' }, String(context.visibleCount)),
]);

const columns: ColumnRegular[] = [
  { prop: 'id', name: 'Work item', size: 112, sortable: true, filter: true },
  { prop: 'title', name: 'Outcome', size: 260, sortable: true, filter: true },
  { prop: 'owner', name: 'Owner', size: 132, sortable: true, filter: true },
  { prop: 'status', name: 'Stage', size: 118, sortable: true, filter: true },
  { prop: 'lane', name: 'Workstream', size: 120, sortable: true, filter: true },
  { prop: 'storyPoints', name: 'Points', size: 86, sortable: true },
  { prop: 'release', name: 'Release', size: 96, sortable: true, filter: true },
  { prop: 'dueDate', name: 'Due', size: 106, sortable: true },
];

export const PRODUCT_DELIVERY_SCENARIO = {
  id: 'product-delivery',
  cardPresentation: 'delivery',
  headerIcons: {
    discovery: 'compass',
    design: 'pen-to-square',
    build: 'screwdriver-wrench',
    review: 'shield-halved',
    released: 'rocket',
  },
  useSwimlanes: true,
  swimlaneLayout: 'top',
  colorScheme: 'light',
  layout: { cardRowHeight: 264, swimlaneWidth: 168, collapsedSwimlaneWidth: 44 },
  eyebrow: 'Product delivery · Release R26.9',
  title: 'From customer signal to a confident release',
  description: 'Keep discovery, product design, delivery, and platform readiness in one view, so every handoff has an owner and customers get the release the team promised.',
  attention: {
    label: 'Build capacity needs a decision',
    detail: 'Build is at 5 of 4 items; Platform carries 3 against its 2-card limit while the event replay fix protects checkout reliability.',
    tone: 'risk',
  },
  metrics: [
    { label: 'Release progress', value: '63%', tone: 'attention' },
    { label: 'Build WIP', value: '5 / 4', tone: 'risk' },
    { label: 'Target release', value: 'Sep 18', tone: 'neutral' },
  ],
  workflowColumns: [
    { prop: 'discovery', name: 'Discovery', size: 334 },
    { prop: 'design', name: 'Design', size: 334 },
    { prop: 'build', name: 'Build', size: 334, wipLimit: 4 },
    { prop: 'review', name: 'Review', size: 334, wipLimit: 4 },
    { prop: 'released', name: 'Released', size: 334 },
  ],
  swimlanes: [
    { id: 'product', title: 'Product experience', collapsible: true, swimlaneTemplate: productSwimlaneTemplate },
    { id: 'platform', title: 'Platform foundations', collapsible: true, wipLimits: { build: 2 }, swimlaneTemplate: productSwimlaneTemplate },
  ],
  wipBehavior: 'warn',
  columns,
  cards: [
    {
      id: 'PD-241',
      title: 'Validate saved-cart recovery signal',
      description: 'Interview returning shoppers and size the failed-session drop-off.',
      status: 'discovery',
      lane: 'product',
      owner: 'Maya Chen',
      assignees: ['Maya Chen', 'Theo Brooks'],
      priority: 'Medium',
      label: 'Research',
      progress: 25,
      dueDate: 'Aug 12',
      order: 1000,
      storyPoints: 3,
      release: 'R26.9',
      handoff: 'Product → Design',
      context: 'R26.9 · 3 pts · Growth',
    },
    {
      id: 'PD-246',
      title: 'Map trust copy for payment retry',
      description: 'Turn decline reasons into clear, localized recovery guidance.',
      status: 'design',
      lane: 'product',
      owner: 'Iris Bell',
      assignees: ['Iris Bell', 'Maya Chen'],
      priority: 'Medium',
      label: 'Content design',
      progress: 55,
      dueDate: 'Aug 14',
      order: 1000,
      storyPoints: 5,
      release: 'R26.9',
      handoff: 'Design → Web',
      context: 'R26.9 · 5 pts · Checkout',
    },
    {
      id: 'PD-249',
      title: 'Prototype delivery promise selector',
      description: 'Test the fastest-versus-greenest choice with real delivery dates.',
      status: 'design',
      lane: 'product',
      owner: 'Iris Bell',
      assignees: ['Iris Bell', 'Ari Singh'],
      priority: 'Medium',
      label: 'Prototype',
      progress: 40,
      dueDate: 'Aug 18',
      order: 2000,
      storyPoints: 8,
      release: 'R26.9',
      handoff: 'Design → Mobile',
      context: 'R26.9 · 8 pts · Delivery',
    },
    {
      id: 'PD-252',
      title: 'Ship resumable checkout sessions',
      description: 'Restore cart, address, and payment intent after an interrupted visit.',
      status: 'build',
      lane: 'product',
      owner: 'Jon Diaz',
      assignees: ['Jon Diaz', 'Elena Park'],
      priority: 'High',
      label: 'Web',
      progress: 70,
      dueDate: 'Aug 28',
      order: 1000,
      storyPoints: 8,
      release: 'R26.9',
      handoff: 'Web → QA',
      context: 'R26.9 · 8 pts · Checkout',
      risk: 'Safari restore is waiting on the token refresh patch.',
    },
    {
      id: 'PD-255',
      title: 'Add order ETA confidence state',
      description: 'Explain when a delivery date is confirmed, estimated, or changing.',
      status: 'build',
      lane: 'product',
      owner: 'Ari Singh',
      assignees: ['Ari Singh', 'Iris Bell'],
      priority: 'Medium',
      label: 'Mobile',
      progress: 60,
      dueDate: 'Sep 2',
      order: 2000,
      storyPoints: 5,
      release: 'R26.9',
      handoff: 'Mobile → QA',
      context: 'R26.9 · 5 pts · Orders',
    },
    {
      id: 'PD-258',
      title: 'Accessibility pass on recovery flow',
      description: 'Verify focus order, errors, and screen-reader recovery announcements.',
      status: 'review',
      lane: 'product',
      owner: 'Nora Reed',
      assignees: ['Nora Reed', 'Jon Diaz'],
      priority: 'High',
      label: 'Accessibility',
      progress: 90,
      dueDate: 'Sep 8',
      order: 1000,
      storyPoints: 3,
      release: 'R26.9',
      handoff: 'QA → Release',
      context: 'R26.9 · 3 pts · Quality',
    },
    {
      id: 'PD-260',
      title: 'Verify analytics acceptance criteria',
      description: 'Confirm recovery, retry, and promise events answer launch questions.',
      status: 'review',
      lane: 'product',
      owner: 'Theo Brooks',
      assignees: ['Theo Brooks', 'Maya Chen'],
      priority: 'Medium',
      label: 'Analytics',
      progress: 88,
      dueDate: 'Sep 10',
      order: 2000,
      storyPoints: 2,
      release: 'R26.9',
      handoff: 'Data → Product',
      context: 'R26.9 · 2 pts · Insights',
    },
    {
      id: 'PD-229',
      title: 'Roll out address autocomplete v2',
      description: 'Released to all markets after conversion and support checks passed.',
      status: 'released',
      lane: 'product',
      owner: 'Jon Diaz',
      assignees: ['Jon Diaz', 'Nora Reed'],
      priority: 'Low',
      label: 'Shipped',
      progress: 100,
      dueDate: 'Aug 7',
      order: 1000,
      storyPoints: 5,
      release: 'R26.8',
      handoff: 'Release → Learn',
      context: 'R26.8 · 5 pts · Conversion',
    },
    {
      id: 'PLAT-114',
      title: 'Size catalog read-model migration',
      description: 'Map schema and rollout options before peak-season inventory growth.',
      status: 'discovery',
      lane: 'platform',
      owner: 'Leon Wu',
      assignees: ['Leon Wu', 'Elena Park'],
      priority: 'Medium',
      label: 'Architecture',
      progress: 20,
      dueDate: 'Aug 13',
      order: 1000,
      storyPoints: 5,
      release: 'R26.9',
      handoff: 'Architecture → Backend',
      context: 'R26.9 · 5 pts · Catalog',
    },
    {
      id: 'PLAT-116',
      title: 'Define checkout idempotency contract',
      description: 'Align web, mobile, and payment retries on one safe request contract.',
      status: 'design',
      lane: 'platform',
      owner: 'Elena Park',
      assignees: ['Elena Park', 'Jon Diaz', 'Ari Singh'],
      priority: 'High',
      label: 'API design',
      progress: 45,
      dueDate: 'Aug 17',
      order: 1000,
      storyPoints: 5,
      release: 'R26.9',
      handoff: 'Backend → Clients',
      context: 'R26.9 · 5 pts · Payments',
    },
    {
      id: 'PLAT-118',
      title: 'Stabilize event replay pipeline',
      description: 'Stop duplicate checkout events before the recovery launch expands.',
      status: 'build',
      lane: 'platform',
      owner: 'Priya Nair',
      assignees: ['Priya Nair', 'Theo Brooks'],
      priority: 'Critical',
      label: 'Reliability',
      progress: 65,
      dueDate: 'Aug 25',
      order: 1000,
      storyPoints: 8,
      release: 'R26.9',
      handoff: 'SRE → Data QA',
      context: 'R26.9 · 8 pts · Events',
      risk: 'Replay lag is consuming 1.7× the agreed error budget.',
    },
    {
      id: 'PLAT-121',
      title: 'Add release cohort kill switch',
      description: 'Let on-call stop one checkout cohort without a full rollback.',
      status: 'build',
      lane: 'platform',
      owner: 'Leon Wu',
      assignees: ['Leon Wu', 'Priya Nair'],
      priority: 'High',
      label: 'Release safety',
      progress: 70,
      dueDate: 'Aug 27',
      order: 2000,
      storyPoints: 5,
      release: 'R26.9',
      handoff: 'Platform → On-call',
      context: 'R26.9 · 5 pts · Controls',
    },
    {
      id: 'PLAT-124',
      title: 'Backfill order promise telemetry',
      description: 'Rebuild missing confidence signals for launch comparison cohorts.',
      status: 'build',
      lane: 'platform',
      owner: 'Theo Brooks',
      assignees: ['Theo Brooks', 'Elena Park'],
      priority: 'Medium',
      label: 'Data',
      progress: 58,
      dueDate: 'Sep 1',
      order: 3000,
      storyPoints: 5,
      release: 'R26.9',
      handoff: 'Data → Analytics',
      context: 'R26.9 · 5 pts · Telemetry',
    },
    {
      id: 'PLAT-126',
      title: 'Load-test session restore API',
      description: 'Prove restore latency under launch traffic and retry bursts.',
      status: 'review',
      lane: 'platform',
      owner: 'Priya Nair',
      assignees: ['Priya Nair', 'Elena Park'],
      priority: 'High',
      label: 'Performance',
      progress: 82,
      dueDate: 'Sep 9',
      order: 1000,
      storyPoints: 3,
      release: 'R26.9',
      handoff: 'Performance → SRE',
      context: 'R26.9 · 3 pts · API',
      risk: 'Current p95 is 430 ms against the 350 ms launch budget.',
    },
    {
      id: 'PLAT-128',
      title: 'Security review token handoff',
      description: 'Close replay and expiry findings for browser-to-payment handoff.',
      status: 'review',
      lane: 'platform',
      owner: 'Elena Park',
      assignees: ['Elena Park', 'Priya Nair'],
      priority: 'High',
      label: 'Security',
      progress: 86,
      dueDate: 'Sep 11',
      order: 2000,
      storyPoints: 3,
      release: 'R26.9',
      handoff: 'Security → Release',
      context: 'R26.9 · 3 pts · Payments',
    },
    {
      id: 'PLAT-108',
      title: 'Publish checkout SLO dashboard',
      description: 'Released shared service health and customer-impact indicators.',
      status: 'released',
      lane: 'platform',
      owner: 'Priya Nair',
      assignees: ['Priya Nair', 'Maya Chen'],
      priority: 'Low',
      label: 'Shipped',
      progress: 100,
      dueDate: 'Aug 6',
      order: 1000,
      storyPoints: 3,
      release: 'R26.8',
      handoff: 'SRE → Product',
      context: 'R26.8 · 3 pts · Observability',
    },
  ],
} satisfies KanbanUseCaseScenario;
