import type { ColumnRegular } from '@revolist/revogrid';
import type { KanbanUseCaseScenario } from '../kanban-use-case-model';

const columns: ColumnRegular[] = [
  { prop: 'id', name: 'Request', size: 108, sortable: true, filter: true },
  { prop: 'title', name: 'Work needed', size: 270, sortable: true, filter: true },
  { prop: 'requester', name: 'Requester', size: 142, sortable: true, filter: true },
  { prop: 'owner', name: 'Owner', size: 142, sortable: true, filter: true },
  { prop: 'department', name: 'Department', size: 126, sortable: true, filter: true },
  { prop: 'status', name: 'Stage', size: 126, sortable: true, filter: true },
  { prop: 'approval', name: 'Approval', size: 190, sortable: true, filter: true },
  { prop: 'requestValue', name: 'Request context', size: 150, sortable: true, filter: true },
  { prop: 'dueDate', name: 'Due', size: 122, sortable: true },
  { prop: 'handoff', name: 'Next handoff', size: 196, sortable: true, filter: true },
];

export const INTERNAL_WORKFLOWS_SCENARIO = {
  id: 'internal-workflows',
  cardPresentation: 'internal-request',
  useSwimlanes: false,
  showDropTargets: true,
  colorScheme: 'light',
  layout: { cardRowHeight: 266, swimlaneWidth: 176, collapsedSwimlaneWidth: 44 },
  eyebrow: 'Internal operations · This week',
  title: 'Make every internal request easy to own—and easier to finish',
  description: 'Bring finance, compliance, procurement, hiring, and IT requests into one accountable flow, so requesters know who is helping and approvers know what needs a decision.',
  attention: {
    label: 'Approval queue needs a decision',
    detail: 'Approval is at 5 of 4 requests; Business Operations carries 3 against its 2-request limit, and Harbor Facilities’ $186k payment must clear today to avoid a service hold.',
    tone: 'risk',
  },
  metrics: [
    { label: 'Open requests', value: '14', tone: 'neutral' },
    { label: 'Approval WIP', value: '5 / 4', tone: 'risk' },
    { label: 'Completed this week', value: '2', tone: 'good' },
  ],
  workflowColumns: [
    { prop: 'intake', name: 'Intake', size: 334, wipLimit: 4 },
    { prop: 'assigned', name: 'Assigned', size: 334, wipLimit: 4 },
    { prop: 'approval', name: 'Approval', size: 334, wipLimit: 4 },
    { prop: 'fulfillment', name: 'Fulfillment', size: 334, wipLimit: 4 },
    { prop: 'complete', name: 'Complete', size: 336 },
  ],
  swimlanes: [
    {
      id: 'business-operations',
      title: 'Business operations',
      collapsible: true,
      wipLimits: { approval: 2 },
    },
    {
      id: 'people-technology',
      title: 'People & technology',
      collapsible: true,
      wipLimits: { fulfillment: 3 },
    },
  ],
  wipBehavior: 'warn',
  columns,
  cards: [
    {
      id: 'IW-201',
      title: 'Record cloud-credit accrual',
      description: 'Capture unused platform credits before the month-end close.',
      status: 'intake',
      lane: 'business-operations',
      owner: 'Marcus Lee',
      requester: 'Emma Ortiz',
      assignees: ['Marcus Lee', 'Emma Ortiz'],
      department: 'Finance',
      approval: 'Controller review',
      requestValue: '$42k accrual',
      handoff: 'Finance Ops → Controller',
      priority: 'Medium',
      label: 'Finance · Accrual',
      progress: 10,
      dueDate: 'Aug 8',
      order: 1000,
      context: 'Finance · Emma Ortiz → Marcus Lee',
    },
    {
      id: 'IW-202',
      title: 'Refresh supplier insurance certificate',
      description: 'Collect current coverage before the facilities renewal is released.',
      status: 'intake',
      lane: 'business-operations',
      owner: 'Nadia Flores',
      requester: 'Jon Diaz',
      assignees: ['Nadia Flores', 'Jon Diaz'],
      department: 'Procurement',
      approval: 'Vendor Risk confirmation',
      requestValue: 'Annual renewal',
      handoff: 'Procurement → Vendor Risk',
      priority: 'Medium',
      label: 'Procurement · Renewal',
      progress: 12,
      dueDate: 'Aug 13',
      order: 2000,
      context: 'Procurement · Jon Diaz → Nadia Flores',
    },
    {
      id: 'IW-203',
      title: 'Screen partner for export controls',
      description: 'Review ownership and destination data for a new EU partnership.',
      status: 'assigned',
      lane: 'business-operations',
      owner: 'Owen Brooks',
      requester: 'Priya Shah',
      assignees: ['Owen Brooks', 'Priya Shah'],
      department: 'Compliance',
      approval: 'Compliance officer review',
      requestValue: 'EU partnership',
      handoff: 'Compliance Ops → Legal',
      priority: 'High',
      label: 'Compliance · Screening',
      progress: 38,
      dueDate: 'Aug 10',
      order: 1000,
      context: 'Compliance · Priya Shah → Owen Brooks',
    },
    {
      id: 'IW-204',
      title: 'Release Harbor Facilities payment',
      description: 'Approve the final invoice before the maintenance coverage cutoff.',
      status: 'approval',
      lane: 'business-operations',
      owner: 'Marcus Lee',
      requester: 'Elena Park',
      assignees: ['Marcus Lee', 'Elena Park', 'Grace Kim'],
      department: 'Finance',
      approval: 'CFO approval',
      requestValue: '$186k invoice',
      handoff: 'Accounts Payable → CFO',
      priority: 'Critical',
      label: 'Finance · Payment',
      progress: 78,
      dueDate: 'Aug 7 · 15:00',
      order: 1000,
      context: 'Finance · Elena Park → Marcus Lee · $186k',
      risk: 'The supplier will place maintenance services on hold if CFO approval misses today’s payment cutoff.',
    },
    {
      id: 'IW-205',
      title: 'Approve laptop fleet purchase order',
      description: 'Release replacement devices before the September hiring cohort.',
      status: 'approval',
      lane: 'business-operations',
      owner: 'Nadia Flores',
      requester: 'Maya Chen',
      assignees: ['Nadia Flores', 'Maya Chen', 'Grace Kim'],
      department: 'Procurement',
      approval: 'VP Finance approval',
      requestValue: '$74k purchase',
      handoff: 'Procurement → Finance',
      priority: 'High',
      label: 'Procurement · Hardware',
      progress: 68,
      dueDate: 'Aug 11',
      order: 2000,
      context: 'Procurement · Maya Chen → Nadia Flores',
    },
    {
      id: 'IW-206',
      title: 'Approve DPA retention exception',
      description: 'Decide whether one regulated customer can retain audit data longer.',
      status: 'approval',
      lane: 'business-operations',
      owner: 'Owen Brooks',
      requester: 'Theo Grant',
      assignees: ['Owen Brooks', 'Theo Grant', 'Priya Shah'],
      department: 'Compliance',
      approval: 'Data Protection Officer decision',
      requestValue: '24-month retention',
      handoff: 'Privacy → Data Protection Officer',
      priority: 'High',
      label: 'Compliance · Privacy',
      progress: 62,
      dueDate: 'Aug 14',
      order: 3000,
      context: 'Compliance · Theo Grant → Owen Brooks',
    },
    {
      id: 'IW-207',
      title: 'Onboard translation services vendor',
      description: 'Create the supplier record and release the localization purchase order.',
      status: 'fulfillment',
      lane: 'business-operations',
      owner: 'Nadia Flores',
      requester: 'Iris Bell',
      assignees: ['Nadia Flores', 'Iris Bell', 'Marcus Lee'],
      department: 'Procurement',
      approval: 'Approved · PO-4821',
      requestValue: '$28k annual',
      handoff: 'Procurement → Finance Systems',
      priority: 'Medium',
      label: 'Procurement · Vendor',
      progress: 82,
      dueDate: 'Aug 18',
      order: 1000,
      context: 'Procurement · Iris Bell → Nadia Flores',
    },
    {
      id: 'IW-208',
      title: 'Reimburse customer workshop travel',
      description: 'Paid the approved expenses and sent the receipt to the requester.',
      status: 'complete',
      lane: 'business-operations',
      owner: 'Marcus Lee',
      requester: 'Sofia Reed',
      assignees: ['Marcus Lee', 'Sofia Reed'],
      department: 'Finance',
      approval: 'Approved · Controller',
      requestValue: '$1.8k expense',
      handoff: 'Finance → Requester',
      priority: 'Low',
      label: 'Finance · Complete',
      progress: 100,
      dueDate: 'Aug 6',
      order: 1000,
      context: 'Finance · Sofia Reed → Marcus Lee',
    },
    {
      id: 'IW-301',
      title: 'Open senior data engineer headcount',
      description: 'Confirm scope and budget before recruiting starts the search.',
      status: 'intake',
      lane: 'people-technology',
      owner: 'Aisha Grant',
      requester: 'Leon Wu',
      assignees: ['Aisha Grant', 'Leon Wu'],
      department: 'Hiring',
      approval: 'VP Engineering review',
      requestValue: '$185k band',
      handoff: 'Talent → Finance',
      priority: 'High',
      label: 'Hiring · Headcount',
      progress: 15,
      dueDate: 'Aug 12',
      order: 1000,
      context: 'Hiring · Leon Wu → Aisha Grant',
    },
    {
      id: 'IW-302',
      title: 'Replace lost security key',
      description: 'Revoke the missing key and issue a replacement before support duty.',
      status: 'assigned',
      lane: 'people-technology',
      owner: 'Devon King',
      requester: 'Caleb Young',
      assignees: ['Devon King', 'Caleb Young'],
      department: 'IT',
      approval: 'Manager confirmed',
      requestValue: 'Privileged access',
      handoff: 'Service Desk → Security',
      priority: 'High',
      label: 'IT · Access',
      progress: 45,
      dueDate: 'Aug 7 · 16:00',
      order: 1000,
      context: 'IT · Caleb Young → Devon King',
    },
    {
      id: 'IW-303',
      title: 'Build Product Ops interview loop',
      description: 'Set the panel, scorecard, and candidate experience before sourcing.',
      status: 'assigned',
      lane: 'people-technology',
      owner: 'Aisha Grant',
      requester: 'Maya Chen',
      assignees: ['Aisha Grant', 'Maya Chen'],
      department: 'Hiring',
      approval: 'Hiring manager review',
      requestValue: '5-person panel',
      handoff: 'Recruiting → Interview panel',
      priority: 'Medium',
      label: 'Hiring · Interview',
      progress: 40,
      dueDate: 'Aug 15',
      order: 2000,
      context: 'Hiring · Maya Chen → Aisha Grant',
    },
    {
      id: 'IW-304',
      title: 'Approve analytics lead offer',
      description: 'Confirm compensation so the recruiter can call the candidate today.',
      status: 'approval',
      lane: 'people-technology',
      owner: 'Aisha Grant',
      requester: 'Leon Wu',
      assignees: ['Aisha Grant', 'Leon Wu', 'Grace Kim'],
      department: 'Hiring',
      approval: 'CFO compensation approval',
      requestValue: '$172k base',
      handoff: 'Talent → CFO',
      priority: 'High',
      label: 'Hiring · Offer',
      progress: 82,
      dueDate: 'Aug 9',
      order: 1000,
      context: 'Hiring · Leon Wu → Aisha Grant',
    },
    {
      id: 'IW-305',
      title: 'Grant NetSuite admin access',
      description: 'Validate separation of duties before adding the finance admin role.',
      status: 'approval',
      lane: 'people-technology',
      owner: 'Devon King',
      requester: 'Marcus Lee',
      assignees: ['Devon King', 'Marcus Lee', 'Priya Shah'],
      department: 'IT',
      approval: 'Finance system owner approval',
      requestValue: 'Admin role',
      handoff: 'IT → System owner',
      priority: 'High',
      label: 'IT · Privileged access',
      progress: 60,
      dueDate: 'Aug 10',
      order: 2000,
      context: 'IT · Marcus Lee → Devon King',
    },
    {
      id: 'IW-306',
      title: 'Prepare laptop for Monday starter',
      description: 'Finish the device, account, and security baseline before day one.',
      status: 'fulfillment',
      lane: 'people-technology',
      owner: 'Devon King',
      requester: 'Aisha Grant',
      assignees: ['Devon King', 'Aisha Grant'],
      department: 'IT',
      approval: 'Security baseline approved',
      requestValue: 'MacBook + access',
      handoff: 'IT → Hiring manager',
      priority: 'High',
      label: 'IT · New starter',
      progress: 88,
      dueDate: 'Aug 8',
      order: 1000,
      context: 'IT · Aisha Grant → Devon King',
    },
    {
      id: 'IW-307',
      title: 'Complete candidate reference checks',
      description: 'Collect two references before the offer committee closes the packet.',
      status: 'fulfillment',
      lane: 'people-technology',
      owner: 'Aisha Grant',
      requester: 'Maya Chen',
      assignees: ['Aisha Grant', 'Maya Chen'],
      department: 'Hiring',
      approval: 'Offer committee pending',
      requestValue: '2 references',
      handoff: 'Recruiting → Hiring manager',
      priority: 'Medium',
      label: 'Hiring · References',
      progress: 72,
      dueDate: 'Aug 11',
      order: 2000,
      context: 'Hiring · Maya Chen → Aisha Grant',
    },
    {
      id: 'IW-308',
      title: 'Clean up dormant SSO groups',
      description: 'Removed stale groups and attached evidence to the access review.',
      status: 'complete',
      lane: 'people-technology',
      owner: 'Devon King',
      requester: 'Priya Shah',
      assignees: ['Devon King', 'Priya Shah'],
      department: 'IT',
      approval: 'Approved · Security',
      requestValue: '11 groups',
      handoff: 'IT → Security audit',
      priority: 'Low',
      label: 'IT · Complete',
      progress: 100,
      dueDate: 'Aug 5',
      order: 1000,
      context: 'IT · Priya Shah → Devon King',
    },
  ],
} satisfies KanbanUseCaseScenario;
